name: Terraform Plan
on:
  pull_request:
    paths: ['infra/terraform/**']

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: "1.7.0" }
      - name: Terraform Init
        run: terraform init
        working-directory: infra/terraform/environments/prod
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      - name: Terraform Plan
        run: terraform plan
        working-directory: infra/terraform/environments/prod
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CF_TOKEN }}
          TF_VAR_yarlis_org_id: ${{ secrets.GCP_ORG_ID }}
          TF_VAR_billing_account: ${{ secrets.GCP_BILLING_ACCOUNT }}
